name: BuildOnSetup

on:
  push:
    branches: [ master, develop, build/migrate-to-poetry ]
  pull_request:
    branches: [ master, develop, build/migrate-to-poetry ]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  [ubuntu-latest, windows-latest, macos-latest] # windows-latest need to figure out how to run on win64
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pipx install poetry==1.5
          poetry install --with dev
      - name: Test with pytest + Coverage
        run: |
          poetry run pytest --html=html/${{ matrix.os }}-test-results-${{ matrix.python-version }}.html
      - name: Upload pytest test results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results-${{ matrix.os }}-${{ matrix.python-version }}
          path: html/${{ matrix.os }}-test-results-${{ matrix.python-version }}.html
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
