name: Linting

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.12 ]

    steps:
      # check-out repo
      - uses: actions/checkout@v2
      - name: Set up ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pipx install poetry==1.8.4
          poetry install --with dev
      # run linters
      - name: Run linters
        run: |
          set -o pipefail
          poetry run make lint
